apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: skahelmdemo
build:
  artifacts:
    - image: 2359721314/skahelm
      jib:
        project: com.example:skaHelmDemo
  tagPolicy:
    envTemplate:
      template: '{{.VERSION}}'
deploy:
  helm:
    releases:
    - name: dev
      chartPath: charts/dev
      valuesFiles:
      - charts/dev/values.yaml
      version: 1.1.0
