apiVersion: v1
description: deploy springboot and mysql via skaffold and helm
name: dev
version: 1.1.0
dependencies:
  - name: redis
    version: "10.5.7"
    repository: https://charts.helm.sh/stable
  - alias: app
    name: skaffold-helm-example
    version: "0.1.0"
    repository: file://../app-release
